### ISSUE TITLE
Custom command

### ISSUE THREAD

**Issue by RageOfFire** [notbeer/Gametest-API-Wrapper#10]
Can you add some examples docs to create custom command .js file ?

**Comment by notbeer** [comment]
It's recommended that you work in the src folder. It's in typescript, so it will show all the classes, methods and more in the IDE. It will help find errors easily too.
To register command do in index.js:
```ts
import { Server } from "../library/Minecraft.js";
Server.command.register({ name: 'ping' }, (data, args) => {
    Server.broadcast('Pong!', data.sender.nameTag);
});
```
Make sure to transpile your code to js
