### ISSUE TITLE
can you make some kind of kit system

### ISSUE THREAD

**Issue by LvckX** [notbeer/Gametest-API-Wrapper#18]
can you make a kit comand like +kit name of kit and it give you the kit or the armor

**Comment by notbeer** [comment]
You can easily do that by registering a custom command

Refer to this link to know how to register a custom command: https://github.com/notbeer/Gametest-API-Wrapper/issues/10#issuecomment-913902711

To give players the kit you can simply save a structure with your kit items and on the command you can structure load that on a player!
